# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGs54u9pLJPLIQDzvU7_clsCO4gbQTj2

## **Assignment 01**
"""

import pandas as pd
# read from csv and excel
df_csv=pd.read_csv("/content/Titanic.csv")
# df_xl=pd.read_excel("");
#  indexing and selecting data
# i want to select age column
print(df_csv["Age"].head())

# Selecting multiple columns
print(df_csv[['Name', 'Age', 'Sex']].head())

# Selecting rows with iloc (first 5 rows)
print(df_csv.iloc[0:5])

# Selecting rows with loc (selecting rows where Survived = 1)
print(df_csv.loc[df_csv['Survived'] == 1])
# i want to sort age column
print(df_csv.sort_values(by="Age").head())
#  above line will sort by default ascending order
#  if we want to sort in descending order then
print(df_csv.sort_values(by="Age",ascending=False).head());

"""# **Assignment 02**"""

import pandas as pd
df=pd.read_csv("/content/Telecom Churn.csv")
print("Dataset Loaded");
#  choosing only numeric column
# Select only numeric columns
num_df = df.select_dtypes(include=['int64', 'float64'])
#  finding minimum of each column
print(num_df.min());
#  lets find max of each column
print(num_df.max());
# lets find mean of the each column
print(num_df.mean());
# lets find range of each column
# this line will give error if ur column contains string value then
# for safer side choose only numeric column perform statistics only to that column
print(num_df.max() - num_df.min());
# lets find variance of each column
print(num_df.var());
# lets find standard deviation of each column
print(num_df.std());
# lets find quantile or percentile
print(num_df.quantile(0.25));
print(num_df.quantile(0.50));
print(num_df.quantile(0.75));

"""imp : num_df = df.select_dtypes(include=['int64', 'float64'])

# **Assignment 03**
"""

import pandas as pd
#  for histogram we need to import matplotlib
import matplotlib.pyplot as plt;
df=pd.read_csv("/House Data.csv");
print("Dataset Loaded");
# select first numeric column
num_df=df.select_dtypes(include=['int64','float64'])
# find variance
print(num_df.var());
# find std deviation
print(num_df.std());
# find percentiles
print(num_df.quantile([0.25,0.5,0.75]));
# plot its histogram
num_df.hist(figsize=(15,12),bins=30);
plt.tight_layout()
# dont forget to show
plt.show()

"""### **Assignment 09**"""

# ----------------------------------------------
# STEP 1: Store all the given points
# ----------------------------------------------
P1 = (0.1, 0.6)
P2 = (0.15, 0.71)
P3 = (0.08, 0.9)
P4 = (0.16, 0.85)
P5 = (0.2, 0.3)
P6 = (0.25, 0.5)
P7 = (0.24, 0.1)
P8 = (0.3, 0.2)

all_points = [P1, P2, P3, P4, P5, P6, P7, P8]

# ----------------------------------------------
# STEP 2: Initialize centroids
# m1 = P1 and m2 = P8
# ----------------------------------------------
m1 = P1   # centroid of Cluster 1
m2 = P8   # centroid of Cluster 2

# ----------------------------------------------
# STEP 3: Define easy distance formula
# Using Euclidean distance
# ----------------------------------------------
def distance(p, m):
    # sqrt( (x1-x2)^2 + (y1-y2)^2 )
    return ((p[0] - m[0])**2 + (p[1] - m[1])**2)**0.5

# ----------------------------------------------
# STEP 4: Assign each point to the nearest centroid
# ----------------------------------------------
C1 = []   # Cluster 1 points
C2 = []   # Cluster 2 points

for p in all_points:
    d1 = distance(p, m1)
    d2 = distance(p, m2)

    # Assign to whichever centroid is closer
    if d1 < d2:
        C1.append(p)
    else:
        C2.append(p)

# ----------------------------------------------
# STEP 5: Compute new centroid m1 (average of C1)
# ----------------------------------------------
x1 = sum(p[0] for p in C1) / len(C1)
y1 = sum(p[1] for p in C1) / len(C1)
m1_new = (x1, y1)

# ----------------------------------------------
# STEP 6: Compute new centroid m2 (average of C2)
# ----------------------------------------------
x2 = sum(p[0] for p in C2) / len(C2)
y2 = sum(p[1] for p in C2) / len(C2)
m2_new = (x2, y2)

# ----------------------------------------------
# STEP 7: Print final answers
# ----------------------------------------------
print("Cluster 1:", C1)
print("Cluster 2:", C2)

# 1) Which cluster does P6 belong to?
print("P6 belongs to Cluster:", "C1" if P6 in C1 else "C2")

# 2) What is the population of Cluster around m2?
print("Population of cluster around m2:", len(C2))

# 3) What are the updated centroids?
print("Updated m1:", m1_new)
print("Updated m2:", m2_new)

"""### **Assignment 10**"""

# -----------------------------
# K-means (k=3) — one assignment step
# Given 8 points and initial centroids
# -----------------------------

# STEP 1: Define points (given)
P1 = (2, 10)
P2 = (2, 5)
P3 = (8, 4)
P4 = (5, 8)
P5 = (7, 5)
P6 = (6, 4)
P7 = (1, 2)
P8 = (4, 9)

all_points = [P1, P2, P3, P4, P5, P6, P7, P8]

# STEP 2: Initialize centroids as given
m1 = P1   # Cluster 1 centroid
m2 = P4   # Cluster 2 centroid
m3 = P7   # Cluster 3 centroid

# STEP 3: Simple Euclidean distance function (no fancy libraries)
def distance(a, b):
    # sqrt((x1-x2)^2 + (y1-y2)^2)
    return ((a[0] - b[0])**2 + (a[1] - b[1])**2) ** 0.5

# STEP 4: Assign each point to the nearest centroid
C1 = []   # will hold points assigned to centroid m1
C2 = []   # will hold points assigned to centroid m2
C3 = []   # will hold points assigned to centroid m3

for p in all_points:
    d1 = distance(p, m1)
    d2 = distance(p, m2)
    d3 = distance(p, m3)

    # compare distances and assign to nearest cluster
    if d1 <= d2 and d1 <= d3:
        C1.append(p)
    elif d2 <= d1 and d2 <= d3:
        C2.append(p)
    else:
        C3.append(p)

# STEP 5: Compute updated centroids (mean of points in each cluster)
# m1_new = mean of C1
if len(C1) > 0:
    m1_new = (sum(x for x,y in C1)/len(C1), sum(y for x,y in C1)/len(C1))
else:
    m1_new = m1  # if cluster empty, keep old centroid

# m2_new = mean of C2
if len(C2) > 0:
    m2_new = (sum(x for x,y in C2)/len(C2), sum(y for x,y in C2)/len(C2))
else:
    m2_new = m2

# m3_new = mean of C3
if len(C3) > 0:
    m3_new = (sum(x for x,y in C3)/len(C3), sum(y for x,y in C3)/len(C3))
else:
    m3_new = m3

# STEP 6: Print results (exam-style)
print("Cluster 1 (around m1):", C1)
print("Cluster 2 (around m2):", C2)
print("Cluster 3 (around m3):", C3)
print()

# 1) Which cluster does P6 belong to?
cluster_of_P6 = "C1" if P6 in C1 else ("C2" if P6 in C2 else "C3")
print("1) P6 belongs to cluster:", cluster_of_P6)

# 2) Population of cluster around m3
print("2) Population around m3 (Cluster 3):", len(C3))

# 3) Updated centroids
print("3) Updated centroids:")
# 3) Updated centroids
print("Updated m1 =", m1_new)
print("Updated m2 =", m2_new)
print("Updated m3 =", m3_new)

"""### **Assignment 11**"""

# # 1. List down the features and their types (e.g., numeric, nominal)
# available in the dataset. 2. Create a histogram for each feature in the
# dataset to illustrate the feature distributions.

import pandas as pd
import matplotlib.pyplot as plt
# read csv
df=pd.read_csv("/content/IRIS.csv")
print("Dataset Loaded")
# features and their data types of each
print("Features and their data types")
print(df.dtypes)
# now create histogram to show distribution
print("Histogram for distribution");
df.hist(figsize=(15,12),bins=10);
#  plot tight_layout kesa layout chahiye asa cahiye
plt.tight_layout();
# dont forget to show the histogram
plt.show()

"""### **Assignment 12**

12.Use Iris flower dataset and perform following :
1. Create a box plot for each feature in the dataset.
2. Identify and discuss distributions and identify outliers from them.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Load the Iris dataset
df = pd.read_csv("/content/IRIS.csv")

# list Of features and their types
print("Features and their data types")
print(df.dtypes)
# Numeric features
features = ["sepal_length", "sepal_width", "petal_length", "petal_width"]

# Create separate box plots for each feature
for col in features:
    plt.figure()  #Creates a new empty graph window.
    plt.boxplot(df[col]) #Draws the box plot for the selected feature/column (df[col]).
    plt.title(f"Box Plot of {col}") # title name do
    plt.xlabel(col) #Labels the X-axis with the column name.
    plt.ylabel("Value")
    plt.show()

"""# **Assignment 13**

13. Use the covid_vaccine_statewise.csv dataset and perform the following
analytics.
a. Describe the dataset
b. Number of persons state wise vaccinated for first dose in India
c. Number of persons state wise vaccinated for second dose in India
"""

import pandas as pd
# dataset import
df=pd.read_csv("/content/Covid Vaccine Statewise.csv")
print("Dataset Loaded")
# describe the dataset
#  1. types of datatypes of each column
# df.dtypes is NOT a function — it is a PROPERTY. () mat lagao
print(df.dtypes)
print(df.info()) #.info() runs a function that prints the dataset summary.
print(df.describe(include='all'))

first_dose = df.groupby("State")["First Dose Administered"].max()
sec_dose=df.groupby("State")["Second Dose Administered"].max()
sec_dose_count=df.groupby("State")["Second Dose Administered"].size()
print(first_dose)
print(sec_dose)
print("Count")
print(sec_dose_count)

"""## **Assignment 14**

14. Use the covid_vaccine_statewise.csv dataset and perform the following
analytics.
A. Describe the dataset.
B. Number of Males vaccinated
C.. Number of females vaccinated
"""

import pandas as pd
df=pd.read_csv("/content/Covid Vaccine Statewise.csv")
#  A. describe the dataset
# 1. check datatypes for each
print(df.dtypes)
# 2. summary of all = info se milega
print(df.info())
# 3. describe the dataset
print(df.describe())
# B . Number of males vaccinated
print(df['Male(Individuals Vaccinated)'].sum())
# C. Number of females vaccinated
print(df['Female(Individuals Vaccinated)'].sum())

"""### **Assignment 15**

15. Use the dataset 'titanic'. The dataset contains 891 rows and contains
information about the passengers who boarded the unfortunate Titanic
ship. Use the Seaborn library to see if we can find any patterns in the data.
"""

import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
df=pd.read_csv("/content/Titanic.csv")
#  lets check basic information
print(df.dtypes)
print(df.describe(include="all"))
print(df.info())
# Pattern 1 → Survival by Gender
sb.countplot(x="Sex", hue="Survived", data=df)
plt.title("Survival Count by Gender")
plt.show()
# Pattern 2 → Survival by Passenger Class
# hue = > y axis k naam
sb.countplot(x="Pclass", hue="Survived", data=df)
plt.title("Survival Count by Passenger Class")
plt.show()
# Pattern 3 → Age distribution
sb.histplot(df["Age"].dropna(), kde=True)
plt.title("Age Distribution of Passengers")
plt.show()
# Pattern 4 → Fare vs Survival
sb.boxplot(x="Survived", y="Fare", data=df)
plt.title("Fare Comparison by Survival")
plt.show()

"""# **Assignment 16**

16. Use the inbuilt dataset 'titanic'. The dataset contains 891 rows and
contains information about the passengers who boarded the unfortunate
Titanic ship. Write a code to check how the price of the ticket (column
name: 'fare') for each passenger is distributed by plotting a histogram.
"""

import pandas as pd
import matplotlib.pyplot as plt
# load the dataset
df=pd.read_csv("/content/Titanic.csv")
# lets describe the dataset
print(df.dtypes)
print(df.info())
print(df.describe())
df.hist(column="Fare", bins=20, figsize=(15,12))
plt.title("Fare distribution of price")
plt.show()

"""# **Assignment 17**

17. Compute Accuracy, Error rate, Precision, Recall for following confusion
matrix ( Use formula for each)

True Positives (TPs): 1 False Positives (FPs): 1
False Negatives (FNs): 8 True Negatives (TNs): 90
"""

# Given confusion matrix values
TP = 1   # True Positives
FP = 1   # False Positives
FN = 8   # False Negatives
TN = 90  # True Negatives

# Total samples
total = TP + FP + FN + TN

# Accuracy
accuracy = (TP + TN) / total

# Error Rate
error_rate = (FP + FN) / total

# Precision
precision = TP / (TP + FP)

# Recall
recall = TP / (TP + FN)

# Print results
print("Accuracy:", accuracy)
print("Error Rate:", error_rate)
print("Precision:", precision)
print("Recall:", recall)

"""## **Assignment 18**

18. Use House_Price prediction dataset. Provide summary statistics (mean,
median, minimum, maximum, standard deviation) of variables (categorical
vs quantitative) such as- For example, if categorical variable is age groups
and quantitative variable is income, then provide summary statistics of
income grouped by the age groups.
"""

import pandas as pd
import matplotlib.pyplot as plt

# loading of dataset
df = pd.read_csv("/House Data.csv")

# numeric columns
num_df = df.select_dtypes(include=['int64','float64'])
print("Numeric columns:", list(num_df.columns))

# numeric summary
print(num_df.min())
print(num_df.max())
print(num_df.mean())
print(num_df.std())
print(num_df.var())

# categorical columns
cat_df = df.select_dtypes(include=['object','category'])
print("Categorical columns:", list(cat_df.columns))

# choose variables (change if needed)
cat_col = "Type"       # categorical variable
num_col = "NumberFloorsofBuilding"    # numeric variable

# summary statistics of numeric grouped by categorical
print(df.groupby(cat_col)[num_col].describe())
print(df.groupby(cat_col)[num_col].agg(['mean','median','min','max','std']))

"""### ***Assignment 19***

19. Write a Python program to display some basic statistical details like
percentile, mean, standard deviation etc (Use python and pandas
commands) the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’
of iris.csv dataset.
"""

import pandas as pd
df=pd.read_csv("/content/IRIS.csv")
print("Dataset loaded")

print(df.head());
print(df.info())
print(df.describe())
print(df.dtypes)

speciesList=df["species"].unique()
print(speciesList)
# lets travel on species list and calculate for each species ka statistics
for sp in speciesList:
    print("\n==============================")
    print("Statistics for Species:", sp)
    print("==============================")

    # Filter rows of one species
    species_df = df[df["species"] == sp]

    # Show basic statistics
    print("Mean:\n", species_df.mean(numeric_only=True))
    print("\nStandard Deviation:\n", species_df.std(numeric_only=True))
    print("\nMinimum Values:\n", species_df.min(numeric_only=True))
    print("\nMaximum Values:\n", species_df.max(numeric_only=True))
    print("\n25th Percentile:\n", species_df.quantile(0.25, numeric_only=True))
    print("\n50th Percentile (Median):\n", species_df.quantile(0.50, numeric_only=True))
    print("\n75th Percentile:\n", species_df.quantile(0.75, numeric_only=True))
    print("\nCount:\n", species_df.count())

"""### **Assignment 20**

20. Write a program to cluster a set of points using K-means for IRIS
dataset. Consider, K=3, clusters. Consider Euclidean distance as the
distance measure. Randomly initialize a cluster mean as one of the data
points. Iterate at least for 10 iterations. After iterations are over, print the
final cluster means for each of the clusters.
"""

import pandas as pd
import random
import math

# Load the data (use the uploaded file)
df = pd.read_csv("/content/IRIS.csv")

# Use only numeric columns for clustering
data = df[["sepal_length", "sepal_width", "petal_length", "petal_width"]].values.tolist()

K = 3
random.seed(42)

# Pick 3 random initial centroids (choose 3 points from data)
indices = random.sample(range(len(data)), K)
centroids = [data[i] for i in indices]

# Run 10 iterations
for it in range(10):
    # create empty clusters
    clusters = [[] for _ in range(K)]

    # Assignment step: assign each point to nearest centroid
    for point in data:
        # compute distances to each centroid
        d0 = math.sqrt((point[0]-centroids[0][0])**2 + (point[1]-centroids[0][1])**2 + (point[2]-centroids[0][2])**2 + (point[3]-centroids[0][3])**2)
        d1 = math.sqrt((point[0]-centroids[1][0])**2 + (point[1]-centroids[1][1])**2 + (point[2]-centroids[1][2])**2 + (point[3]-centroids[1][3])**2)
        d2 = math.sqrt((point[0]-centroids[2][0])**2 + (point[1]-centroids[2][1])**2 + (point[2]-centroids[2][2])**2 + (point[3]-centroids[2][3])**2)

        # find smallest distance and append to that cluster
        if d0 <= d1 and d0 <= d2:
            clusters[0].append(point)
        elif d1 <= d0 and d1 <= d2:
            clusters[1].append(point)
        else:
            clusters[2].append(point)

    # Update step: compute new centroids (mean of each cluster)
    new_centroids = []
    for c in clusters:
        if len(c) == 0:
            new_centroids.append(centroids[len(new_centroids)])  # keep old if empty
        else:
            sx = sum(p[0] for p in c)
            sy = sum(p[1] for p in c)
            sz = sum(p[2] for p in c)
            sw = sum(p[3] for p in c)
            n = len(c)
            new_centroids.append([sx/n, sy/n, sz/n, sw/n])
    centroids = new_centroids
    print(f"Iteration {it+1}: cluster sizes = {[len(c) for c in clusters]}")

# Final centroids
print("\nFinal centroids:")
for i, c in enumerate(centroids, 1):
    print(f" m{i} =", [round(v,4) for v in c])

"""### **Assignment 21**

21. Write a program to cluster a set of points using K-means for IRIS
dataset. Consider, K=4, clusters. Consider Euclidean distance as the
distance measure. Randomly initialize a cluster mean as one of the data
points. Iterate at least for 10 iterations. After iterations are over, print the
final cluster means for each of the clusters.
"""

import pandas as pd
import random
import math

# Load dataset
df = pd.read_csv("/content/IRIS.csv")

# Only numeric features
data = df[["sepal_length", "sepal_width", "petal_length", "petal_width"]].values.tolist()

# K = 4 clusters
K = 4
random.seed(42)

# Randomly choose 4 initial centroids
initial_indices = random.sample(range(len(data)), K)
centroids = [data[i] for i in initial_indices]

print("Initial centroids:")
for i, c in enumerate(centroids, 1):
    print(f"m{i} =", c)

# Function for Euclidean distance
def distance(p, c):
    return math.sqrt(
        (p[0]-c[0])**2 +
        (p[1]-c[1])**2 +
        (p[2]-c[2])**2 +
        (p[3]-c[3])**2
    )

# Run K-means for 10 iterations
for it in range(10):
    clusters = [[] for _ in range(K)]

    # Assign points to nearest centroid
    for point in data:
        d_list = [distance(point, centroids[i]) for i in range(K)]
        nearest = d_list.index(min(d_list))
        clusters[nearest].append(point)

    # Update centroids = mean of cluster points
    new_centroids = []
    for cluster in clusters:
        if len(cluster) == 0:
            new_centroids.append([0,0,0,0])  # avoid division error
        else:
            x = sum(p[0] for p in cluster)/len(cluster)
            y = sum(p[1] for p in cluster)/len(cluster)
            z = sum(p[2] for p in cluster)/len(cluster)
            w = sum(p[3] for p in cluster)/len(cluster)
            new_centroids.append([x, y, z, w])

    centroids = new_centroids
    print(f"Iteration {it+1}: cluster sizes = {[len(c) for c in clusters]}")

# Print final 4 centroids
print("\nFinal centroids after 10 iterations:")
for i, c in enumerate(centroids, 1):
    print(f"Cluster {i} centroid:", [round(val,4) for val in c])

"""### **Assignment 23**

23. With reference to Table , obtain the Frequency table for the
attribute age. From the frequency table you have obtained, calculate the
information gain of the frequency table while splitting on Age. (Use step
by step Python/Pandas commands)
"""

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_excel("/content/Age Table.xlsx")

# STEP 1: Frequency table
freq = pd.crosstab(df["Age"], df["Class"])
print("Frequency Table:\n", freq, "\n")

# Entropy function
def entropy(col):
    probs = col.value_counts(normalize=True)
    return -(probs * np.log2(probs)).sum()

# STEP 2: Parent entropy
entropy_full = entropy(df["Class"])
print("Entropy of Full Dataset:", entropy_full, "\n")

# STEP 3: Entropy of each Age group
entropy_young = entropy(df[df["Age"]=="Young"]["Class"])
entropy_middle = entropy(df[df["Age"]=="Middle"]["Class"])
entropy_old = entropy(df[df["Age"]=="Old"]["Class"])

print("Entropy Young:", entropy_young)
print("Entropy Middle:", entropy_middle)
print("Entropy Old:", entropy_old, "\n")

# STEP 4: Weighted entropy after splitting on Age
N = len(df)
entropy_after = (
    (len(df[df["Age"]=="Young"]) / N) * entropy_young +
    (len(df[df["Age"]=="Middle"]) / N) * entropy_middle +
    (len(df[df["Age"]=="Old"]) / N) * entropy_old
)

print("Entropy After Split:", entropy_after, "\n")

# STEP 5: Information Gain
IG = entropy_full - entropy_after
print("Information Gain for Age:", IG)

"""**25. Perform Data Cleaning, Data transformation using Python on any data set**"""

import pandas as pd
import numpy as np

# ------------------ 1) Load Dataset ------------------
df = pd.read_excel("/mnt/data/Age Table.xlsx")
print("Original Dataset:")
print(df.head())


# ------------------ 2) DATA CLEANING ------------------

# (A) Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# (B) Fill missing numeric columns with mean
num_cols = df.select_dtypes(include=[np.number]).columns
for col in num_cols:
    df[col] = df[col].fillna(df[col].mean())

# (C) Fill missing categorical columns with mode
cat_cols = df.select_dtypes(include=["object"]).columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("\nAfter Filling Missing Values:")
print(df.isnull().sum())


# (D) Remove duplicate rows (if any)
df = df.drop_duplicates()
print("\nAfter Removing Duplicates:")
print(df)


# ------------------ 3) DATA TRANSFORMATION ------------------

# (A) Convert categorical to category-type
if "Age" in df.columns:
    df["Age"] = df["Age"].astype("category")

# (B) One-hot encoding (dummy variables)
df_dummies = pd.get_dummies(df, drop_first=True)
print("\nAfter One-Hot Encoding:")
print(df_dummies.head())

# (C) Normalize numeric columns (Min-Max scaling)
for col in num_cols:
    df_dummies[col+"_scaled"] = (df_dummies[col] - df_dummies[col].min()) / (df_dummies[col].max() - df_dummies[col].min())

print("\nAfter Scaling Numeric Columns:")
print(df_dummies.head())


# ------------------ 4) Save Cleaned + Transformed Data ------------------
df_dummies.to_csv("/mnt/data/Cleaned_Transformed_Data.csv", index=False)
print("\nCleaned & Transformed Dataset Saved.")